# Site
repository: PiyushTri/PiyushTripathyResume
favicon: images/favicon.ico

# Personal info
name: Piyush Kumar Tripathy
title: System Engineer at Tata Consultancy Services (TCS)
email: tripathyprince1993@gmail.com
website: www.github.com/PiyushTri/PiyushTripathyResume

# Social links
#twitter_username: facespics
github_username:    PiyushTri
# dribbble_username: jekyll
 facebook_username: piyush.kr.tripathy
# flickr_username: jekyll
instagram_username: paarth_photography
linkedin_username: piyush
# pinterest_username: jekyll
youtube_username:  piyush
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Piyush and I'm a System Engineer . As well as administrating systems I also have experience making software and web apps. I have worked at a number of projects gaining teamwork and leadership skills.
Testing URL


 #Projects Section
 projects_title: | # this will include new lines to allow paragraphs
  Hi, my name's Piyush and I'm a System Engineer . As well as administrating systems I also have experience making software and web apps. I have worked at a number of projects gaining teamwork and leadership skills.

# Experience Section
 experience_title: | # this will include new lines to allow paragraphs
  Hi, my name's Piyush and I'm a System Engineer . As well as administrating systems I also have experience making software and web apps. I have worked at a number of projects gaining teamwork and leadership skills.

# Education Section
 educaton_title: | # this will include new lines to allow paragraphs
  Hi, my name's Piyush and I'm a System Engineer . As well as administrating systems I also have experience making software and web apps. I have worked at a number of projects gaining teamwork and leadership skills.

# More Section
 more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [ Smart Photo Frame](http://smartphotoframe.herokuapp.com)



sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
