# Site
repository: PiyushTri/PiyushTripathyResume
favicon: images/favicon.ico

# Personal info
name: Piyush Kumar Tripathy
title: System Engineer at Tata Consultancy Services (TCS)
email: tripathyprince1993@gmail.com
website: www.github.com/TriPiyush/PiyushTripathyResume

# Social links
#twitter_username: facespics
github_username:  TriPiyush
# dribbble_username: jekyll
 facebook_username: piyush.kr.tripathy
# flickr_username: jekyll
instagram_username: paarth_photography
linkedin_username: 
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Piyush and I'm a System Engineer . As well as administrating systems I also have experience making software and web apps. I have worked at a number of projects gaining teamwork and leadership skills.



 Projects Section
 projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
